import sharedConfig from "@offerleaks/eslint-config/next.js";

/** @type {import("eslint").Linter.Config[]} */
const config = [
  // next-env.d.ts is auto-generated and regenerated by `next dev`/`next build` -- never hand-edited, never linted.
  { ignores: [".next/**", "node_modules/**", "next-env.d.ts"] },
  ...sharedConfig,
];

export default config;
