"""add analyses and verdicts tables

Revision ID: 568093daa50f
Revises: dd39f47bd008
Create Date: 2026-08-09 07:31:04.149811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '568093daa50f'
down_revision: Union[str, Sequence[str], None] = 'dd39f47bd008'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyses',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('file_storage_key', sa.String(length=512), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'complete', 'failed', 'needs_manual_review', name='analysis_status'), server_default='pending', nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analyses_status'), 'analyses', ['status'], unique=False)
    op.create_index(op.f('ix_analyses_user_id'), 'analyses', ['user_id'], unique=False)
    op.create_table('verdicts',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('analysis_id', sa.Uuid(), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['analyses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdicts_analysis_id'), 'verdicts', ['analysis_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdicts_analysis_id'), table_name='verdicts')
    op.drop_table('verdicts')
    op.drop_index(op.f('ix_analyses_user_id'), table_name='analyses')
    op.drop_index(op.f('ix_analyses_status'), table_name='analyses')
    op.drop_table('analyses')
    # ### end Alembic commands ###
    # Same known Alembic/Postgres ENUM limitation as
    # dd39f47bd008_add_users_table.py's downgrade: DROP TYPE isn't emitted
    # automatically on table drop.
    sa.Enum(name='analysis_status').drop(op.get_bind(), checkfirst=True)
    # Same known Alembic/Postgres ENUM-on-table-drop limitation handled in
    # dd39f47bd008 -- without this, re-running upgrade after a downgrade
    # fails with "type already exists".
    sa.Enum(name='analysis_status').drop(op.get_bind(), checkfirst=True)
    # Alembic's autogenerate does not emit DROP TYPE for Postgres ENUMs on
    # table drop (same known limitation noted in the Version 2 users-table
    # migration) -- without this, re-running upgrade after a downgrade
    # fails with "type already exists".
    sa.Enum(name='analysis_status').drop(op.get_bind(), checkfirst=True)
